# Generated by Django 4.2.24 on 2025-09-23 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_formsubmission_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Field Option', 'verbose_name_plural': 'Field Options'},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Form Submission', 'verbose_name_plural': 'Form Submissions'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Submission File', 'verbose_name_plural': 'Submission Files'},
        ),
        migrations.AddField(
            model_name='page',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='If true, only authenticated users may submit this page'),
        ),
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower order renders earlier'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='data',
            field=models.JSONField(default=dict, help_text='Submitted form data: field_name -> value'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata (user agent, etc)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional - the authenticated user who submitted the form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false the page will not be served by the API'),
        ),
    ]
