"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

This settings file is tailored for local development with Docker + Postgres,
and includes Django REST Framework, django-cors-headers, and djangorestframework-simplejwt.
Make sure to set environment variables in your docker-compose.yml or your shell:
- DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
- DEBUG (1 or 0)
- DJANGO_SECRET_KEY (optional; fallback to a default dev key below)
- DJANGO_ALLOWED_HOSTS (space-separated hosts, optional; default is localhost)
- DJANGO_CORS_ALLOWED_ORIGINS (optional; comma-separated origins for production)
- DJANGO_CSRF_TRUSTED_ORIGINS (optional; comma-separated origins for CSRF)
"""

import os
from pathlib import Path
from datetime import timedelta

# BASE_DIR like: project_root/backend/
BASE_DIR = Path(__file__).resolve().parent.parent

# Read secret key from env for safety; fallback to local dev key only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-*irx1715636mi1dt8gyu4z_!q2035hyugq3h!9kpo6kzmpbx%z",
)

# DEBUG: set to "0" in production. Default to development ON.
DEBUG = os.environ.get("DEBUG", "1") == "1"

# Allowed hosts: read from env (space-separated), or default to localhost and 127.0.0.1.
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1").split()

# Application definition
INSTALLED_APPS = [
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",  # JWT support

    # Your apps
    "jobs",
]

MIDDLEWARE = [
    # corsheaders should be as high as possible so it can add CORS headers before other middleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Add any project-level template dirs here if you use them
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# -------------------------------------------------------------------------
# Database
# Try to use Postgres settings from environment (as provided by docker-compose).
# If none provided, default to a local SQLite file for convenience.
# -------------------------------------------------------------------------
if os.environ.get("DB_NAME") and os.environ.get("DB_USER"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "jobportal"),
            "USER": os.environ.get("DB_USER", "jobuser"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "jobpass"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    # fallback to sqlite for quick local dev without docker
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# -------------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------------
# Internationalization & Time zone
# -------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

# Set to your local timezone. Default to Asia/Dhaka as you mentioned earlier.
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Asia/Dhaka")

USE_I18N = True
USE_L10N = True
USE_TZ = True

# -------------------------------------------------------------------------
# Static & Media files (development-friendly defaults)
# -------------------------------------------------------------------------
STATIC_URL = "/static/"
# when collecting static in production, set STATIC_ROOT
STATIC_ROOT = BASE_DIR / "staticfiles"
# optional: useful during development when serving static files from project
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------------------------------
# Django REST Framework
# - Use JWTAuthentication for API clients, and keep SessionAuthentication so
#   browsable API / admin session access still works in DEBUG/dev.
# - In production you may want to change DEFAULT_RENDERER_CLASSES to JSON only.
# -------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    # Use Browsable API only in DEBUG, otherwise JSONRenderer only
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        *([] if not DEBUG else ("rest_framework.renderers.BrowsableAPIRenderer",))
    ),
    # You can add pagination, throttling, etc. here later.
}

# -------------------------------------------------------------------------
# djangorestframework-simplejwt settings
# -------------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("SIMPLE_JWT_ACCESS_MINUTES", "60"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("SIMPLE_JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Additional options can be added here (ALGORITHM, SIGNING_KEY, etc.)
}

# -------------------------------------------------------------------------
# CORS / CSRF settings
# For local development we allow all origins. In production set DJANGO_CORS_ALLOWED_ORIGINS
# to a comma-separated list of allowed origins (e.g. "https://example.com,https://app.example.com").
# Also supports DJANGO_CSRF_TRUSTED_ORIGINS + DJANGO_ALLOWED_HOSTS.
# -------------------------------------------------------------------------
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    # read comma-separated origins from env, fallback to empty list
    cors_origins = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "")
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins.split(",") if o.strip()]
    CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins (useful when frontend runs on different host)
csrf_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_origins.split(",") if o.strip()]

# -------------------------------------------------------------------------
# Logging (simple console logger for development)
# -------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

# -------------------------------------------------------------------------
# Default primary key field type
# -------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
