version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobportal_db
      POSTGRES_USER: jobportal_user
      POSTGRES_PASSWORD: jobportal_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"    # 🔹 host 5433 -> container 5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8001:8000"    # host 8001 -> container 8000 (your 8000 is busy)
    command: >
      sh -c "python manage.py migrate --noinput || true && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

volumes:
  db_data:
