# Generated by Django 5.2.7 on 2025-10-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('name', models.SlugField(help_text='Unique name for this field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('password', 'Password'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Dropdown'), ('file', 'File Upload')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Used in URL, e.g. 'registration'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.field')),
            ],
            options={
                'verbose_name': 'Field Option',
                'verbose_name_plural': 'Field Options',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.page'),
        ),
    ]
